### ISSUE TITLE
GPU out of memory problem

### ISSUE THREAD

**Issue by jind11** [nlpdata/mrc_bert_baseline#1]
Hi, I have one question and need your help: how do you manage to fit the bert large model into the GPU with train batch size of 24? Thanks!

**Comment by accreator** [comment]
Hi, you can try using a larger _gradient_accumulation_steps_. 
The reported BERT-Large results are obtained using the following parameters on 8 P40 GPUs: train_batch_size=24, gradient_accumulation_steps=3

**Comment by jind11** [comment]
Thanks for the response! I have tried this command: "CUDA_VISIBLE_DEVICES=1,2,3,4 python run_classifier.py --task_name dream --do_train --do_eval --data_dir .  --vocab_file $BERT_BASE_DIR/vocab.txt --bert_config_file $BERT_BASE_DIR/bert_config.json --init_checkpoint $BERT_BASE_DIR/pytorch_model.bin --max_seq_length 512 --train_batch_size 24 --learning_rate 2e-5 --num_train_epochs 16.0 --output_dir dream_finetuned_large_2 --gradient_accumulation_steps 3" on a 4 Titan X GPU station, however, it seems that the model is spreaded into 4 gpus, instead it tried to fit all data into GPU 0 and thus OOM problem was encountered. Have you come across similar issues? If so, how to sovle it? Thanks!

**Comment by accreator** [comment]
When using 4 GPUs (with batch size 24 and BERT-Large), gradient_accumulation_steps may need to be set to 6, so each GPU at a time works on one instance (i.e., train_batch_size / #gpu / gradient_accumulation_steps = 1). Under this setting, we did not encounter similar OOM issues on a 4 P40 GPU station, though I am not sure if it works on your station since the memory of Titan X is smaller.
